@startuml Context Diagram - Hotel System

title Hotel System: DFD 0

!define RECTANGLE class

rectangle "Khách hàng" as Customer
rectangle "Lễ tân" as Receptionist


component "Hệ thống khách sạn" as HotelSystem

HotelSystem --> Customer : Thông tin phòng
Customer --> HotelSystem : Thông tin đặt phòng
HotelSystem --> Customer : Thông tin hoá đơn

HotelSystem --> Receptionist : Thông tin đặt phòng
HotelSystem --> Receptionist : Thông tin phòng
Receptionist --> HotelSystem : Thông tin hoá đơn

@enduml
